#pragma once

namespace cudaPhysics
{
    template <typename Real>
	__host__ __device__ void calc_neohookean_P(Real *P, const Real *F, Real mu, Real lambda)
	{
		Real invF[9];
		Real invFT[9];
		matInv3(invF, F);
		matTrans3(invFT, invF);
		Real J = det3(F);

		Real temp1[9];
		Real temp2[9];
		vecSubs(temp1, F, invFT, 9);
		matMul3(temp1, mu, temp1);
		matMul3(temp2, lambda * log(J), invFT);
		vecAdd(P, temp1, temp2, 9);
	}

    /**
     * @brief Calculate K * u for the Neohookean force. K = (partial f / partial x). u is a vector to replace (delta x)
     * @details See SIGGRAPH 2012 Course "FEM Simulation of 3D Deformable Solids ...." Chapter 4.3 for more details.
     * (delta K) can be derived as some formulas with (delta x).
     * To get K * u, we can replace (delta x) with u in the formulas.
     * @param Ku The output K * u (length 12)
     * @param Ds The Ds matrix of the tetrahedron (length 9)
     * @param partial_Ds The partial Ds matrix derived from (delta x) replaced by u (length 9)
     */
    template <typename Real>
    __host__ __device__ void calc_neohookean_K_mul_u(
        Real *Ku,
        const Real *Ds,
        const Real *partial_Ds,
        const Real *InvDm,
        Real W,
        Real mu,
        Real lambda
    )
    {
        Real F[9], partial_F[9], F_inv[9], J;
        matMul3(F, Ds, InvDm);
        matMul3(partial_F, partial_Ds, InvDm);
        matInv3(F_inv, F);
        J = det3(F);

        Real P1[9], P2[9], P2_T[9], F_inv_mul_partial_F[9], P3[9], P3_T[9];
        vecMul(P1, mu, partial_F, 9);

        matMul3(F_inv_mul_partial_F, F_inv, partial_F);
        matMul3(P2_T, F_inv_mul_partial_F, F_inv);
        matTrans3(P2, P2_T);
        vecMul(P2, mu - lambda * log(J), P2, 9);

        Real trace = F_inv_mul_partial_F[0] + F_inv_mul_partial_F[4] + F_inv_mul_partial_F[8];
        vecMul(P3_T, lambda * trace, F_inv, 9);
        matTrans3(P3, P3_T);

        Real partial_P[9], partial_H[9];
        axpbypcz(partial_P, (Real)1.0, P1, (Real)1.0, P2, (Real)1.0, P3, 9);
        matmatTMul3(partial_H, partial_P, InvDm);
        vecMul(partial_H, -W, partial_H, 9);

        cudaPhysics::matTrans3(&Ku[3], partial_H);
        for (unsigned int j = 0; j < 3; ++j)
            Ku[j] = -(Ku[j + 3] + Ku[j + 6] + Ku[j + 9]);
    }
    
    /**
     * @brief Calculate the K = (partial f / partial x) of the Neohookean force
     * @details Generated by sympy
     * See ./sympy_utils/neohookean_diag.py for details
     * @param K The diagonal part of the output stiffness matrix (length 12)
     * each 3 entries correspond to one vertex of the tetrahedron
     */
    template <typename Real>
    __host__ __device__ void calc_neohookean_K_diag(
        Real *K,
        const Real *x0,
        const Real *x1,
        const Real *x2,
        const Real *x3,
        const Real *InvDm,
        Real W,
        Real mu,
        Real lambda)
    {
        double t0 = InvDm[0*3+1]*InvDm[1*3+2];
        double t1 = t0*x1[2];
        double t2 = t1*x0[1];
        double t3 = x0[2]*x2[1];
        double t4 = t0*t3;
        double t5 = x1[1]*x2[2];
        double t6 = t0*t5;
        double t7 = InvDm[0*3+1]*InvDm[2*3+2];
        double t8 = t7*x1[2];
        double t9 = t8*x0[1];
        double t10 = x0[2]*x3[1];
        double t11 = t10*t7;
        double t12 = x1[1]*x3[2];
        double t13 = t12*t7;
        double t14 = x0[1]*x2[2];
        double t15 = InvDm[0*3+2]*InvDm[1*3+1];
        double t16 = t14*t15;
        double t17 = x0[2]*x1[1];
        double t18 = t15*t17;
        double t19 = x1[2]*x2[1];
        double t20 = t15*t19;
        double t21 = x0[1]*x3[2];
        double t22 = InvDm[0*3+2]*InvDm[2*3+1];
        double t23 = t21*t22;
        double t24 = t17*t22;
        double t25 = x1[2]*x3[1];
        double t26 = t22*t25;
        double t27 = InvDm[1*3+1]*InvDm[2*3+2];
        double t28 = t14*t27;
        double t29 = t10*t27;
        double t30 = x2[1]*x3[2];
        double t31 = t27*t30;
        double t32 = InvDm[1*3+2]*InvDm[2*3+1];
        double t33 = t21*t32;
        double t34 = t3*t32;
        double t35 = x2[2]*x3[1];
        double t36 = t32*t35;
        double t37 = InvDm[0*3+1]*InvDm[1*3+2]*x0[1]*x2[2] + InvDm[0*3+1]*InvDm[1*3+2]*x0[2]*x1[1] + InvDm[0*3+1]*InvDm[1*3+2]*x1[2]*x2[1] + InvDm[0*3+1]*InvDm[2*3+2]*x0[1]*x3[2] + InvDm[0*3+1]*InvDm[2*3+2]*x0[2]*x1[1] + InvDm[0*3+1]*InvDm[2*3+2]*x1[2]*x3[1] + InvDm[0*3+2]*InvDm[1*3+1]*x0[1]*x1[2] + InvDm[0*3+2]*InvDm[1*3+1]*x0[2]*x2[1] + InvDm[0*3+2]*InvDm[1*3+1]*x1[1]*x2[2] + InvDm[0*3+2]*InvDm[2*3+1]*x0[1]*x1[2] + InvDm[0*3+2]*InvDm[2*3+1]*x0[2]*x3[1] + InvDm[0*3+2]*InvDm[2*3+1]*x1[1]*x3[2] + InvDm[1*3+1]*InvDm[2*3+2]*x0[1]*x3[2] + InvDm[1*3+1]*InvDm[2*3+2]*x0[2]*x2[1] + InvDm[1*3+1]*InvDm[2*3+2]*x2[2]*x3[1] + InvDm[1*3+2]*InvDm[2*3+1]*x0[1]*x2[2] + InvDm[1*3+2]*InvDm[2*3+1]*x0[2]*x3[1] + InvDm[1*3+2]*InvDm[2*3+1]*x2[1]*x3[2] - t11 - t13 - t16 - t18 - t2 - t20 - t23 - t24 - t26 - t28 - t29 - t31 - t33 - t34 - t36 - t4 - t6 - t9;
        double t38 = InvDm[0*3+0]*t27;
        double t39 = t38*t5;
        double t40 = t25*t38;
        double t41 = InvDm[0*3+0]*t31;
        double t42 = InvDm[0*3+0]*t21*t27;
        double t43 = x0[1]*x1[2];
        double t44 = t38*t43;
        double t45 = InvDm[0*3+0]*t28;
        double t46 = InvDm[0*3+0]*t27*t3;
        double t47 = t17*t38;
        double t48 = InvDm[0*3+0]*t29;
        double t49 = InvDm[0*3+0]*t27*t35;
        double t50 = t12*t38;
        double t51 = t19*t38;
        double t52 = InvDm[0*3+0]*t32;
        double t53 = t12*t52;
        double t54 = t19*t52;
        double t55 = InvDm[0*3+0]*t36;
        double t56 = InvDm[0*3+0]*t14*t32;
        double t57 = t43*t52;
        double t58 = InvDm[0*3+0]*t33;
        double t59 = InvDm[0*3+0]*t10*t32;
        double t60 = t17*t52;
        double t61 = InvDm[0*3+0]*t34;
        double t62 = InvDm[0*3+0]*t30*t32;
        double t63 = t5*t52;
        double t64 = t25*t52;
        double t65 = InvDm[1*3+0]*t13;
        double t66 = t8*x0[0];
        double t67 = InvDm[1*3+0]*t66;
        double t68 = InvDm[1*3+0]*t7;
        double t69 = t35*t68;
        double t70 = t14*t68;
        double t71 = InvDm[1*3+0]*t9;
        double t72 = t21*t7;
        double t73 = InvDm[1*3+0]*x2[0];
        double t74 = InvDm[1*3+0]*t11;
        double t75 = t17*t7;
        double t76 = t3*t68;
        double t77 = t30*t68;
        double t78 = t5*t68;
        double t79 = InvDm[1*3+0]*t8*x3[1];
        double t80 = InvDm[2*3+0]*t6;
        double t81 = t1*x0[0];
        double t82 = InvDm[2*3+0]*t81;
        double t83 = InvDm[2*3+0]*t0;
        double t84 = t30*t83;
        double t85 = t21*t83;
        double t86 = InvDm[2*3+0]*t2;
        double t87 = t0*t14;
        double t88 = InvDm[2*3+0]*x3[0];
        double t89 = InvDm[2*3+0]*t4;
        double t90 = t0*t17;
        double t91 = t10*t83;
        double t92 = t35*t83;
        double t93 = t12*t83;
        double t94 = InvDm[2*3+0]*t1*x2[1];
        double t95 = InvDm[1*3+0]*t22;
        double t96 = t5*t95;
        double t97 = InvDm[1*3+0]*t26;
        double t98 = t30*t95;
        double t99 = InvDm[1*3+0]*t23;
        double t100 = t22*t43;
        double t101 = t14*t95;
        double t102 = t3*t95;
        double t103 = InvDm[1*3+0]*t24;
        double t104 = t10*t22;
        double t105 = t35*t95;
        double t106 = InvDm[1*3+0]*t12*t22;
        double t107 = t19*t95;
        double t108 = InvDm[2*3+0]*t15;
        double t109 = t108*t12;
        double t110 = InvDm[2*3+0]*t20;
        double t111 = t108*t35;
        double t112 = InvDm[2*3+0]*t16;
        double t113 = t15*t43;
        double t114 = t108*t21;
        double t115 = t10*t108;
        double t116 = InvDm[2*3+0]*t18;
        double t117 = t15*t3;
        double t118 = t108*t30;
        double t119 = InvDm[2*3+0]*t15*t5;
        double t120 = t108*t25;
        double t121 = InvDm[1*3+0]*t72;
        double t122 = InvDm[1*3+0]*t75;
        double t123 = t8*x3[0];
        double t124 = InvDm[1*3+0]*t123;
        double t125 = InvDm[2*3+0]*t87;
        double t126 = InvDm[2*3+0]*t90;
        double t127 = t1*x2[0];
        double t128 = InvDm[2*3+0]*t127;
        double t129 = InvDm[1*3+0]*t100;
        double t130 = InvDm[1*3+0]*t104;
        double t131 = InvDm[2*3+0]*t113;
        double t132 = InvDm[2*3+0]*t117;
        double t133 = t100*t73 - t101*x1[0] + t101*x3[0] + t102*x1[0] - t102*x3[0] + t103*x3[0] + t104*t73 - t105*x0[0] + t105*x1[0] - t106*x0[0] + t106*x2[0] - t107*x0[0] + t107*x3[0] + t109*x0[0] - t109*x2[0] - t11*t73 + t110*x0[0] - t110*x3[0] + t111*x0[0] - t111*x1[0] + t112*x1[0] + t113*t88 - t114*x1[0] + t114*x2[0] + t115*x1[0] - t115*x2[0] + t116*x2[0] + t117*t88 - t118*x0[0] + t118*x1[0] - t119*x0[0] + t119*x3[0] - t120*x0[0] + t120*x2[0] - t121*x1[0] - t122*x3[0] - t124*x2[1] - t125*x1[0] - t126*x2[0] - t128*x3[1] - t129*x3[0] - t130*x1[0] - t131*x2[0] - t132*x1[0] - t16*t88 - t18*t88 - t2*t88 - t23*t73 - t24*t73 + t39*x0[0] - t39*x3[0] - t4*t88 + t40*x0[0] - t40*x2[0] + t41*x0[0] - t41*x1[0] + t42*x1[0] - t42*x2[0] + t44*x2[0] - t44*x3[0] - t45*x1[0] + t45*x3[0] + t46*x1[0] - t46*x3[0] - t47*x2[0] + t47*x3[0] - t48*x1[0] + t48*x2[0] - t49*x0[0] + t49*x1[0] - t50*x0[0] + t50*x2[0] - t51*x0[0] + t51*x3[0] + t53*x0[0] - t53*x2[0] + t54*x0[0] - t54*x3[0] + t55*x0[0] - t55*x1[0] + t56*x1[0] - t56*x3[0] - t57*x2[0] + t57*x3[0] - t58*x1[0] + t58*x2[0] + t59*x1[0] - t59*x2[0] + t60*x2[0] - t60*x3[0] - t61*x1[0] + t61*x3[0] - t62*x0[0] + t62*x1[0] - t63*x0[0] + t63*x3[0] - t64*x0[0] + t64*x2[0] + t65*x0[0] - t65*x2[0] + t67*x2[1] + t69*x0[0] - t69*x1[0] + t70*x1[0] - t70*x3[0] + t71*x3[0] + t72*t73 + t73*t75 - t73*t9 + t74*x1[0] - t76*x1[0] + t76*x3[0] - t77*x0[0] + t77*x1[0] - t78*x0[0] + t78*x3[0] - t79*x0[0] + t79*x2[0] + t80*x0[0] - t80*x3[0] + t82*x3[1] + t84*x0[0] - t84*x1[0] + t85*x1[0] - t85*x2[0] + t86*x2[0] + t87*t88 + t88*t90 + t89*x1[0] - t91*x1[0] + t91*x2[0] - t92*x0[0] + t92*x1[0] - t93*x0[0] + t93*x2[0] - t94*x0[0] + t94*x3[0] + t96*x0[0] - t96*x3[0] + t97*x0[0] - t97*x2[0] + t98*x0[0] - t98*x1[0] + t99*x1[0];
        double t134 = (Real)pow(t133, -2);
        double t135 = InvDm[2*3+0]*t1;
        double t136 = t135*x3[1];
        double t137 = -t105 + t111 - t118 + t41 - t49 + t55 - t62 + t69 - t77 + t84 - t92 + t98;
        double t138 = InvDm[1*3+0]*t8;
        double t139 = -t107 + t110 - t119 + t138*x2[1] + t39 - t51 + t54 - t63 - t78 + t80 - t94 + t96;
        double t140 = t106 - t109 + t120 - t136 - t137 - t139 - t40 + t50 - t53 + t64 - t65 + t79 + t93 - t97;
        double t141 = t134*t140;
        double t142 = t141*t37;
        double t143 = InvDm[0*3+0] + InvDm[1*3+0] + InvDm[2*3+0];
        double t144 = -t133;
        double t145 = lambda*log(t144);
        double t146 = lambda/(t133*t144);
        double t147 = t140*t146;
        double t148 = W*(mu*(-t142 - t143) + t142*t145 + t147*t37);
        double t149 = InvDm[0*3+0]*InvDm[1*3+2];
        double t150 = InvDm[0*3+0]*InvDm[2*3+2];
        double t151 = InvDm[0*3+2]*InvDm[1*3+0];
        double t152 = InvDm[0*3+2]*InvDm[2*3+0];
        double t153 = InvDm[1*3+0]*InvDm[2*3+2];
        double t154 = InvDm[1*3+2]*InvDm[2*3+0];
        double t155 = t10*t150 - t10*t152 + t10*t153 - t10*t154 + t12*t150 - t12*t152 - t14*t149 + t14*t151 + t14*t153 - t14*t154 - t149*t17 - t149*t19 + t149*t3 + t149*t43 + t149*t5 - t150*t17 - t150*t21 - t150*t25 + t150*t43 + t151*t17 + t151*t19 - t151*t3 - t151*t43 - t151*t5 + t152*t17 + t152*t21 + t152*t25 - t152*t43 - t153*t21 - t153*t3 + t153*t30 - t153*t35 + t154*t21 + t154*t3 - t154*t30 + t154*t35;
        double t156 = t141*t155;
        double t157 = InvDm[0*3+1] + InvDm[1*3+1] + InvDm[2*3+1];
        double t158 = W*(mu*(-t156 - t157) + t145*t156 + t147*t155);
        double t159 = InvDm[0*3+0]*InvDm[1*3+1];
        double t160 = InvDm[0*3+0]*InvDm[2*3+1];
        double t161 = InvDm[0*3+1]*InvDm[1*3+0];
        double t162 = InvDm[0*3+1]*InvDm[2*3+0];
        double t163 = InvDm[1*3+0]*InvDm[2*3+1];
        double t164 = InvDm[1*3+1]*InvDm[2*3+0];
        double t165 = InvDm[0*3+0]*InvDm[1*3+1]*x0[1]*x2[2] + InvDm[0*3+0]*InvDm[1*3+1]*x0[2]*x1[1] + InvDm[0*3+0]*InvDm[1*3+1]*x1[2]*x2[1] + InvDm[0*3+0]*InvDm[2*3+1]*x0[1]*x3[2] + InvDm[0*3+0]*InvDm[2*3+1]*x0[2]*x1[1] + InvDm[0*3+0]*InvDm[2*3+1]*x1[2]*x3[1] + InvDm[0*3+1]*InvDm[1*3+0]*x0[1]*x1[2] + InvDm[0*3+1]*InvDm[1*3+0]*x0[2]*x2[1] + InvDm[0*3+1]*InvDm[1*3+0]*x1[1]*x2[2] + InvDm[0*3+1]*InvDm[2*3+0]*x0[1]*x1[2] + InvDm[0*3+1]*InvDm[2*3+0]*x0[2]*x3[1] + InvDm[0*3+1]*InvDm[2*3+0]*x1[1]*x3[2] + InvDm[1*3+0]*InvDm[2*3+1]*x0[1]*x3[2] + InvDm[1*3+0]*InvDm[2*3+1]*x0[2]*x2[1] + InvDm[1*3+0]*InvDm[2*3+1]*x2[2]*x3[1] + InvDm[1*3+1]*InvDm[2*3+0]*x0[1]*x2[2] + InvDm[1*3+1]*InvDm[2*3+0]*x0[2]*x3[1] + InvDm[1*3+1]*InvDm[2*3+0]*x2[1]*x3[2] - t10*t160 - t10*t163 - t12*t160 - t14*t161 - t14*t163 - t159*t3 - t159*t43 - t159*t5 - t160*t43 - t161*t17 - t161*t19 - t162*t17 - t162*t21 - t162*t25 - t163*t30 - t164*t21 - t164*t3 - t164*t35;
        double t166 = t141*t165;
        double t167 = InvDm[0*3+2] + InvDm[1*3+2] + InvDm[2*3+2];
        double t168 = W*(mu*(-t166 - t167) + t145*t166 + t147*t165);
        double t169 = x0[2]*x2[0];
        double t170 = t0*t169;
        double t171 = t0*x2[2];
        double t172 = t171*x1[0];
        double t173 = x0[2]*x3[0];
        double t174 = t173*t7;
        double t175 = t7*x3[2];
        double t176 = t175*x1[0];
        double t177 = x0[0]*x2[2];
        double t178 = t15*t177;
        double t179 = x0[2]*x1[0];
        double t180 = t15*t179;
        double t181 = t15*x1[2];
        double t182 = t181*x2[0];
        double t183 = x0[0]*x3[2];
        double t184 = t183*t22;
        double t185 = t179*t22;
        double t186 = t22*x1[2];
        double t187 = t186*x3[0];
        double t188 = t177*t27;
        double t189 = t173*t27;
        double t190 = x2[0]*x3[2];
        double t191 = t190*t27;
        double t192 = t183*t32;
        double t193 = t169*t32;
        double t194 = x2[2]*x3[0];
        double t195 = t194*t32;
        double t196 = t171*x0[0];
        double t197 = t0*t179;
        double t198 = t175*x0[0];
        double t199 = t179*t7;
        double t200 = t181*x0[0];
        double t201 = t15*t169;
        double t202 = x1[0]*x2[2];
        double t203 = t15*t202;
        double t204 = t186*x0[0];
        double t205 = t173*t22;
        double t206 = x1[0]*x3[2];
        double t207 = t206*t22;
        double t208 = t183*t27;
        double t209 = t169*t27;
        double t210 = t194*t27;
        double t211 = t177*t32;
        double t212 = t173*t32;
        double t213 = t190*t32;
        double t214 = -t123 - t127 + t170 + t172 + t174 + t176 + t178 + t180 + t182 + t184 + t185 + t187 + t188 + t189 + t191 + t192 + t193 + t195 - t196 - t197 - t198 - t199 - t200 - t201 - t203 - t204 - t205 - t207 - t208 - t209 - t210 - t211 - t212 - t213 + t66 + t81;
        double t215 = x1[2]*x3[0];
        double t216 = t215*t38;
        double t217 = t206*t52;
        double t218 = InvDm[1*3+0]*t176;
        double t219 = t135*x3[0];
        double t220 = InvDm[1*3+0]*t187;
        double t221 = t108*t206;
        double t222 = t206*t38;
        double t223 = t215*t52;
        double t224 = t206*t83;
        double t225 = InvDm[1*3+0]*t207;
        double t226 = t181*t88;
        double t227 = InvDm[0*3+0]*t191 + InvDm[0*3+0]*t195 - InvDm[0*3+0]*t210 - InvDm[0*3+0]*t213 - t108*t190 + t108*t194 - t171*t88 - t175*t73 + t190*t83 + t190*t95 + t194*t68 - t194*t95;
        double t228 = x1[2]*x2[0];
        double t229 = InvDm[2*3+0]*t172 + InvDm[2*3+0]*t182 - InvDm[2*3+0]*t203 - t128 + t138*x2[0] - t186*t73 + t202*t38 - t202*t52 - t202*t68 + t202*t95 - t228*t38 + t228*t52;
        double t230 = -t124 + t216 + t217 + t218 + t219 + t220 + t221 - t222 - t223 - t224 - t225 - t226 + t227 + t229;
        double t231 = t134*t230;
        double t232 = t214*t231;
        double t233 = t146*t230;
        double t234 = W*(mu*(-t143 - t232) + t145*t232 + t214*t233);
        double t235 = InvDm[0*3+0]*InvDm[1*3+2]*x0[0]*x2[2] + InvDm[0*3+0]*InvDm[1*3+2]*x0[2]*x1[0] + InvDm[0*3+0]*InvDm[1*3+2]*x1[2]*x2[0] + InvDm[0*3+0]*InvDm[2*3+2]*x0[0]*x3[2] + InvDm[0*3+0]*InvDm[2*3+2]*x0[2]*x1[0] + InvDm[0*3+0]*InvDm[2*3+2]*x1[2]*x3[0] + InvDm[0*3+2]*InvDm[1*3+0]*x0[0]*x1[2] + InvDm[0*3+2]*InvDm[1*3+0]*x0[2]*x2[0] + InvDm[0*3+2]*InvDm[1*3+0]*x1[0]*x2[2] + InvDm[0*3+2]*InvDm[2*3+0]*x0[0]*x1[2] + InvDm[0*3+2]*InvDm[2*3+0]*x0[2]*x3[0] + InvDm[0*3+2]*InvDm[2*3+0]*x1[0]*x3[2] + InvDm[1*3+0]*InvDm[2*3+2]*x0[0]*x3[2] + InvDm[1*3+0]*InvDm[2*3+2]*x0[2]*x2[0] + InvDm[1*3+0]*InvDm[2*3+2]*x2[2]*x3[0] + InvDm[1*3+2]*InvDm[2*3+0]*x0[0]*x2[2] + InvDm[1*3+2]*InvDm[2*3+0]*x0[2]*x3[0] + InvDm[1*3+2]*InvDm[2*3+0]*x2[0]*x3[2] - t149*t169 - t149*t202 - t149*x0[0]*x1[2] - t150*t173 - t150*t206 - t150*x0[0]*x1[2] - t151*t177 - t151*t179 - t151*t228 - t152*t179 - t152*t183 - t152*t215 - t153*t173 - t153*t177 - t153*t190 - t154*t169 - t154*t183 - t154*t194;
        double t236 = t231*t235;
        double t237 = W*(mu*(-t157 - t236) + t145*t236 + t233*t235);
        double t238 = x0[0]*x1[2];
        double t239 = t159*t169 - t159*t177 - t159*t179 + t159*t202 - t159*t228 + t159*t238 + t160*t173 - t160*t179 - t160*t183 + t160*t206 - t160*t215 + t160*t238 - t161*t169 + t161*t177 + t161*t179 - t161*t202 + t161*t228 - t161*t238 - t162*t173 + t162*t179 + t162*t183 - t162*t206 + t162*t215 - t162*t238 - t163*t169 + t163*t173 + t163*t177 - t163*t183 + t163*t190 - t163*t194 + t164*t169 - t164*t173 - t164*t177 + t164*t183 - t164*t190 + t164*t194;
        double t240 = t231*t239;
        double t241 = W*(mu*(-t167 - t240) + t145*t240 + t233*t239);
        double t242 = t0*x1[1];
        double t243 = t242*x0[0];
        double t244 = x0[1]*x2[0];
        double t245 = t0*t244;
        double t246 = x1[0]*x2[1];
        double t247 = t0*t246;
        double t248 = t7*x1[1];
        double t249 = t248*x0[0];
        double t250 = x0[1]*x3[0];
        double t251 = t250*t7;
        double t252 = x1[0]*x3[1];
        double t253 = t252*t7;
        double t254 = x0[0]*x2[1];
        double t255 = t15*t254;
        double t256 = x0[1]*x1[0];
        double t257 = t15*t256;
        double t258 = x1[1]*x2[0];
        double t259 = t15*t258;
        double t260 = x0[0]*x3[1];
        double t261 = t22*t260;
        double t262 = t22*t256;
        double t263 = x1[1]*x3[0];
        double t264 = t22*t263;
        double t265 = t254*t27;
        double t266 = t250*t27;
        double t267 = x2[0]*x3[1];
        double t268 = t267*t27;
        double t269 = t260*t32;
        double t270 = t244*t32;
        double t271 = x2[1]*x3[0];
        double t272 = t271*t32;
        double t273 = InvDm[0*3+1]*InvDm[1*3+2]*x0[0]*x2[1] + InvDm[0*3+1]*InvDm[1*3+2]*x0[1]*x1[0] + InvDm[0*3+1]*InvDm[1*3+2]*x1[1]*x2[0] + InvDm[0*3+1]*InvDm[2*3+2]*x0[0]*x3[1] + InvDm[0*3+1]*InvDm[2*3+2]*x0[1]*x1[0] + InvDm[0*3+1]*InvDm[2*3+2]*x1[1]*x3[0] + InvDm[0*3+2]*InvDm[1*3+1]*x0[0]*x1[1] + InvDm[0*3+2]*InvDm[1*3+1]*x0[1]*x2[0] + InvDm[0*3+2]*InvDm[1*3+1]*x1[0]*x2[1] + InvDm[0*3+2]*InvDm[2*3+1]*x0[0]*x1[1] + InvDm[0*3+2]*InvDm[2*3+1]*x0[1]*x3[0] + InvDm[0*3+2]*InvDm[2*3+1]*x1[0]*x3[1] + InvDm[1*3+1]*InvDm[2*3+2]*x0[0]*x3[1] + InvDm[1*3+1]*InvDm[2*3+2]*x0[1]*x2[0] + InvDm[1*3+1]*InvDm[2*3+2]*x2[1]*x3[0] + InvDm[1*3+2]*InvDm[2*3+1]*x0[0]*x2[1] + InvDm[1*3+2]*InvDm[2*3+1]*x0[1]*x3[0] + InvDm[1*3+2]*InvDm[2*3+1]*x2[0]*x3[1] - t243 - t245 - t247 - t249 - t251 - t253 - t255 - t257 - t259 - t261 - t262 - t264 - t265 - t266 - t268 - t269 - t270 - t272;
        double t274 = t263*t38;
        double t275 = t252*t52;
        double t276 = InvDm[1*3+0]*t253;
        double t277 = t242*t88;
        double t278 = InvDm[1*3+0]*t264;
        double t279 = t108*t252;
        double t280 = t252*t38;
        double t281 = t263*t52;
        double t282 = InvDm[1*3+0]*t248*x3[0];
        double t283 = t252*t83;
        double t284 = InvDm[1*3+0]*t22*t252;
        double t285 = t108*t263;
        double t286 = -InvDm[0*3+0]*t267*t32 + InvDm[0*3+0]*t268 - InvDm[0*3+0]*t27*t271 + InvDm[0*3+0]*t272 - t108*t267 + t108*t271 - t267*t68 + t267*t83 + t267*t95 + t271*t68 - t271*t83 - t271*t95;
        double t287 = -InvDm[2*3+0]*t15*t246 - InvDm[2*3+0]*t242*x2[0] + InvDm[2*3+0]*t247 + InvDm[2*3+0]*t259 + t246*t38 - t246*t52 - t246*t68 + t246*t95 + t248*t73 - t258*t38 + t258*t52 - t258*t95;
        double t288 = -t274 - t275 - t276 - t277 - t278 - t279 + t280 + t281 + t282 + t283 + t284 + t285 - t286 - t287;
        double t289 = t134*t288;
        double t290 = t273*t289;
        double t291 = t146*t288;
        double t292 = W*(mu*(-t143 - t290) + t145*t290 + t273*t291);
        double t293 = x0[0]*x1[1];
        double t294 = t149*t244 + t149*t246 - t149*t254 - t149*t256 - t149*t258 + t149*t293 + t150*t250 + t150*t252 - t150*t256 - t150*t260 - t150*t263 + t150*t293 - t151*t244 - t151*t246 + t151*t254 + t151*t256 + t151*t258 - t151*t293 - t152*t250 - t152*t252 + t152*t256 + t152*t260 + t152*t263 - t152*t293 - t153*t244 + t153*t250 + t153*t254 - t153*t260 + t153*t267 - t153*t271 + t154*t244 - t154*t250 - t154*t254 + t154*t260 - t154*t267 + t154*t271;
        double t295 = t289*t294;
        double t296 = W*(mu*(-t157 - t295) + t145*t295 + t291*t294);
        double t297 = InvDm[0*3+0]*InvDm[1*3+1]*x0[0]*x2[1] + InvDm[0*3+0]*InvDm[1*3+1]*x0[1]*x1[0] + InvDm[0*3+0]*InvDm[1*3+1]*x1[1]*x2[0] + InvDm[0*3+0]*InvDm[2*3+1]*x0[0]*x3[1] + InvDm[0*3+0]*InvDm[2*3+1]*x0[1]*x1[0] + InvDm[0*3+0]*InvDm[2*3+1]*x1[1]*x3[0] + InvDm[0*3+1]*InvDm[1*3+0]*x0[0]*x1[1] + InvDm[0*3+1]*InvDm[1*3+0]*x0[1]*x2[0] + InvDm[0*3+1]*InvDm[1*3+0]*x1[0]*x2[1] + InvDm[0*3+1]*InvDm[2*3+0]*x0[0]*x1[1] + InvDm[0*3+1]*InvDm[2*3+0]*x0[1]*x3[0] + InvDm[0*3+1]*InvDm[2*3+0]*x1[0]*x3[1] + InvDm[1*3+0]*InvDm[2*3+1]*x0[0]*x3[1] + InvDm[1*3+0]*InvDm[2*3+1]*x0[1]*x2[0] + InvDm[1*3+0]*InvDm[2*3+1]*x2[1]*x3[0] + InvDm[1*3+1]*InvDm[2*3+0]*x0[0]*x2[1] + InvDm[1*3+1]*InvDm[2*3+0]*x0[1]*x3[0] + InvDm[1*3+1]*InvDm[2*3+0]*x2[0]*x3[1] - t159*t244 - t159*t246 - t159*t293 - t160*t250 - t160*t252 - t160*t293 - t161*t254 - t161*t256 - t161*t258 - t162*t256 - t162*t260 - t162*t263 - t163*t250 - t163*t254 - t163*t267 - t164*t244 - t164*t260 - t164*t271;
        double t298 = t289*t297;
        double t299 = W*(mu*(-t167 - t298) + t145*t298 + t291*t297);
        double t300 = t114 - t115 + t121 + t130 - t42 + t48 + t58 - t59 - t74 - t85 + t91 - t99;
        double t301 = t101 - t102 - t112 + t125 + t132 + t137 + t300 + t45 - t46 - t56 + t61 - t70 + t76 - t89;
        double t302 = t134*t301;
        double t303 = t302*t37;
        double t304 = t146*t301;
        double t305 = InvDm[0*3+0]*W;
        double t306 = t155*t302;
        double t307 = InvDm[0*3+1]*W;
        double t308 = t165*t302;
        double t309 = InvDm[0*3+2]*W;
        double t310 = InvDm[0*3+0]*t188;
        double t311 = InvDm[0*3+0]*t193;
        double t312 = t169*t68;
        double t313 = InvDm[2*3+0]*t196;
        double t314 = t177*t95;
        double t315 = InvDm[2*3+0]*t201;
        double t316 = InvDm[0*3+0]*t209;
        double t317 = InvDm[0*3+0]*t211;
        double t318 = t177*t68;
        double t319 = InvDm[2*3+0]*t170;
        double t320 = t169*t95;
        double t321 = InvDm[2*3+0]*t178;
        double t322 = InvDm[0*3+0]*t189 + InvDm[0*3+0]*t192 - InvDm[0*3+0]*t208 - InvDm[0*3+0]*t212 - InvDm[1*3+0]*t174 - InvDm[1*3+0]*t184 + InvDm[1*3+0]*t198 + InvDm[1*3+0]*t205 - t108*t173 + t108*t183 + t173*t83 - t183*t83;
        double t323 = -t227 - t310 - t311 - t312 - t313 - t314 - t315 + t316 + t317 + t318 + t319 + t320 + t321 - t322;
        double t324 = t134*t323;
        double t325 = t214*t324;
        double t326 = t146*t323;
        double t327 = t235*t324;
        double t328 = t239*t324;
        double t329 = InvDm[0*3+0]*t265;
        double t330 = InvDm[0*3+0]*t270;
        double t331 = t244*t68;
        double t332 = InvDm[2*3+0]*t0*t254;
        double t333 = t254*t95;
        double t334 = InvDm[2*3+0]*t15*t244;
        double t335 = InvDm[0*3+0]*t244*t27;
        double t336 = InvDm[0*3+0]*t254*t32;
        double t337 = t254*t68;
        double t338 = InvDm[2*3+0]*t245;
        double t339 = t244*t95;
        double t340 = InvDm[2*3+0]*t255;
        double t341 = -InvDm[0*3+0]*t250*t32 - InvDm[0*3+0]*t260*t27 + InvDm[0*3+0]*t266 + InvDm[0*3+0]*t269 + InvDm[1*3+0]*t22*t250 - InvDm[1*3+0]*t251 + InvDm[1*3+0]*t260*t7 - InvDm[1*3+0]*t261 - t108*t250 + t108*t260 + t250*t83 - t260*t83;
        double t342 = t286 + t329 + t330 + t331 + t332 + t333 + t334 - t335 - t336 - t337 - t338 - t339 - t340 + t341;
        double t343 = t134*t342;
        double t344 = t273*t343;
        double t345 = t146*t342;
        double t346 = t294*t343;
        double t347 = t297*t343;
        double t348 = -t103 + t116 + t122 - t126 + t129 - t131 + t44 - t47 - t57 + t60 - t71 + t86;
        double t349 = -t106 + t109 - t120 + t136 - t300 - t348 + t40 - t50 + t53 - t64 + t65 - t79 - t93 + t97;
        double t350 = t134*t349;
        double t351 = t350*t37;
        double t352 = t146*t349;
        double t353 = InvDm[1*3+0]*W;
        double t354 = t155*t350;
        double t355 = InvDm[1*3+1]*W;
        double t356 = t165*t350;
        double t357 = InvDm[1*3+2]*W;
        double t358 = -InvDm[1*3+0]*t185 + InvDm[1*3+0]*t199 + InvDm[1*3+0]*t204 + InvDm[2*3+0]*t180 - InvDm[2*3+0]*t197 - InvDm[2*3+0]*t200 - t179*t38 + t179*t52 + t238*t38 - t238*t52 - t67 + t82;
        double t359 = t124 - t216 - t217 - t218 - t219 - t220 - t221 + t222 + t223 + t224 + t225 + t226 + t322 + t358;
        double t360 = t134*t359;
        double t361 = t214*t360;
        double t362 = t146*t359;
        double t363 = t235*t360;
        double t364 = t239*t360;
        double t365 = InvDm[1*3+0]*t22*t293 - InvDm[1*3+0]*t249 + InvDm[1*3+0]*t256*t7 - InvDm[1*3+0]*t262 - InvDm[2*3+0]*t0*t256 - InvDm[2*3+0]*t15*t293 + InvDm[2*3+0]*t243 + InvDm[2*3+0]*t257 - t256*t38 + t256*t52 + t293*t38 - t293*t52;
        double t366 = t274 + t275 + t276 + t277 + t278 + t279 - t280 - t281 - t282 - t283 - t284 - t285 - t341 - t365;
        double t367 = t134*t366;
        double t368 = t273*t367;
        double t369 = t146*t366;
        double t370 = t294*t367;
        double t371 = t297*t367;
        double t372 = -t101 + t102 + t112 - t125 - t132 + t139 + t348 - t45 + t46 + t56 - t61 + t70 - t76 + t89;
        double t373 = t134*t372;
        double t374 = t37*t373;
        double t375 = t146*t372;
        double t376 = InvDm[2*3+0]*W;
        double t377 = t155*t373;
        double t378 = InvDm[2*3+1]*W;
        double t379 = t165*t373;
        double t380 = InvDm[2*3+2]*W;
        double t381 = -t229 + t310 + t311 + t312 + t313 + t314 + t315 - t316 - t317 - t318 - t319 - t320 - t321 - t358;
        double t382 = t134*t381;
        double t383 = t214*t382;
        double t384 = t146*t381;
        double t385 = t235*t382;
        double t386 = t239*t382;
        double t387 = t287 - t329 - t330 - t331 - t332 - t333 - t334 + t335 + t336 + t337 + t338 + t339 + t340 + t365;
        double t388 = t134*t387;
        double t389 = t273*t388;
        double t390 = t146*t387;
        double t391 = t294*t388;
        double t392 = t297*t388;
        K[0] = (Real)(InvDm[0*3+0]*t148 + InvDm[0*3+1]*t158 + InvDm[0*3+2]*t168 + InvDm[1*3+0]*t148 + InvDm[1*3+1]*t158 + InvDm[1*3+2]*t168 + InvDm[2*3+0]*t148 + InvDm[2*3+1]*t158 + InvDm[2*3+2]*t168);
        K[1] = (Real)(InvDm[0*3+0]*t234 + InvDm[0*3+1]*t237 + InvDm[0*3+2]*t241 + InvDm[1*3+0]*t234 + InvDm[1*3+1]*t237 + InvDm[1*3+2]*t241 + InvDm[2*3+0]*t234 + InvDm[2*3+1]*t237 + InvDm[2*3+2]*t241);
        K[2] = (Real)(InvDm[0*3+0]*t292 + InvDm[0*3+1]*t296 + InvDm[0*3+2]*t299 + InvDm[1*3+0]*t292 + InvDm[1*3+1]*t296 + InvDm[1*3+2]*t299 + InvDm[2*3+0]*t292 + InvDm[2*3+1]*t296 + InvDm[2*3+2]*t299);
        K[3] = (Real)(-t305*(mu*(InvDm[0*3+0] - t303) + t145*t303 + t304*t37) - t307*(mu*(InvDm[0*3+1] - t306) + t145*t306 + t155*t304) - t309*(mu*(InvDm[0*3+2] - t308) + t145*t308 + t165*t304));
        K[4] = (Real)(-t305*(mu*(InvDm[0*3+0] - t325) + t145*t325 + t214*t326) - t307*(mu*(InvDm[0*3+1] - t327) + t145*t327 + t235*t326) - t309*(mu*(InvDm[0*3+2] - t328) + t145*t328 + t239*t326));
        K[5] = (Real)(-t305*(mu*(InvDm[0*3+0] - t344) + t145*t344 + t273*t345) - t307*(mu*(InvDm[0*3+1] - t346) + t145*t346 + t294*t345) - t309*(mu*(InvDm[0*3+2] - t347) + t145*t347 + t297*t345));
        K[6] = (Real)(-t353*(mu*(InvDm[1*3+0] - t351) + t145*t351 + t352*t37) - t355*(mu*(InvDm[1*3+1] - t354) + t145*t354 + t155*t352) - t357*(mu*(InvDm[1*3+2] - t356) + t145*t356 + t165*t352));
        K[7] = (Real)(-t353*(mu*(InvDm[1*3+0] - t361) + t145*t361 + t214*t362) - t355*(mu*(InvDm[1*3+1] - t363) + t145*t363 + t235*t362) - t357*(mu*(InvDm[1*3+2] - t364) + t145*t364 + t239*t362));
        K[8] = (Real)(-t353*(mu*(InvDm[1*3+0] - t368) + t145*t368 + t273*t369) - t355*(mu*(InvDm[1*3+1] - t370) + t145*t370 + t294*t369) - t357*(mu*(InvDm[1*3+2] - t371) + t145*t371 + t297*t369));
        K[9] = (Real)(-t376*(mu*(InvDm[2*3+0] - t374) + t145*t374 + t37*t375) - t378*(mu*(InvDm[2*3+1] - t377) + t145*t377 + t155*t375) - t380*(mu*(InvDm[2*3+2] - t379) + t145*t379 + t165*t375));
        K[10] = (Real)(-t376*(mu*(InvDm[2*3+0] - t383) + t145*t383 + t214*t384) - t378*(mu*(InvDm[2*3+1] - t385) + t145*t385 + t235*t384) - t380*(mu*(InvDm[2*3+2] - t386) + t145*t386 + t239*t384));
        K[11] = (Real)(-t376*(mu*(InvDm[2*3+0] - t389) + t145*t389 + t273*t390) - t378*(mu*(InvDm[2*3+1] - t391) + t145*t391 + t294*t390) - t380*(mu*(InvDm[2*3+2] - t392) + t145*t392 + t297*t390));
    }
}
