function(add_example name)
    foreach(module IN ITEMS ${ARGN})
        if(NOT TARGET ${module})
            return()
        endif()
    endforeach()

    message(STATUS "Creating viewer examples: ${name}")
    file(GLOB_RECURSE sources ${CMAKE_CURRENT_SOURCE_DIR}/${name}/*.cpp ${CMAKE_CURRENT_SOURCE_DIR}/${name}/*.cu ${CMAKE_CURRENT_SOURCE_DIR}/common.cpp)
    add_executable(${name} ${sources})
    target_include_directories(${name} PRIVATE ${CMAKE_CURRENT_SOURCE_DIR})
    target_link_libraries(${name} PRIVATE ${ARGN})

    set_target_properties(${name} PROPERTIES FOLDER Examples)
endfunction()

macro(subdirlist result curdir)
    file(GLOB children RELATIVE ${curdir} ${curdir}/*)
    set(dirlist "")
    foreach(child ${children})
        if(IS_DIRECTORY ${curdir}/${child})
            list(APPEND dirlist ${child})
        endif()
    endforeach()
    set(${result} ${dirlist})
endmacro()

subdirlist(subdirs ${CMAKE_CURRENT_SOURCE_DIR})
configure_file(${CMAKE_CURRENT_SOURCE_DIR}/example_config.h.in ${CMAKE_CURRENT_SOURCE_DIR}/example_config.h)

foreach(dir ${subdirs})
    add_example(${dir} viewer Physics)
endforeach()
